<a href="https://colab.research.google.com/github/SujalS14/Daily-News-for-Stock-Market-Prediction_BAAI_CP/blob/main/week2_sql_(original_backup).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd, sqlite3
df = pd.read_csv("https://raw.githubusercontent.com/SujalS14/Daily-News-for-Stock-Market-Prediction_BAAI_CP/refs/heads/main/Combined_News_DJIA%202.csv")
df = df.drop_duplicates().dropna()
df.columns = (df.columns.str.strip().str.lower().str.replace(" ", "_"))

In [20]:
conn = sqlite3.connect(":memory:")
df.to_sql("data", conn, index=False)
def q(sql):return pd.read_sql(sql,conn)

In [21]:
q("SELECT * FROM data LIMIT 5")

,date,label,top1,top2,top3,top4,top5,top6,top7,top8,...,top16,top17,top18,top19,top20,top21,top22,top23,top24,top25
0,2008-08-08,0,"b""Georgia 'downs two Russian warplanes' as cou...",b'BREAKING: Musharraf to be impeached.',b'Russia Today: Columns of troops roll into So...,b'Russian tanks are moving towards the capital...,"b""Afghan children raped with 'impunity,' U.N. ...",b'150 Russian tanks have entered South Ossetia...,"b""Breaking: Georgia invades South Ossetia, Rus...","b""The 'enemy combatent' trials are nothing but...",...,b'Georgia Invades South Ossetia - if Russia ge...,b'Al-Qaeda Faces Islamist Backlash',"b'Condoleezza Rice: ""The US would not act to p...",b'This is a busy day: The European Union has ...,"b""Georgia will withdraw 1,000 soldiers from Ir...",b'Why the Pentagon Thinks Attacking Iran is a ...,b'Caucasus in crisis: Georgia invades South Os...,b'Indian shoe manufactory - And again in a se...,b'Visitors Suffering from Mental Illnesses Ban...,"b""No Help for Mexico's Kidnapping Surge"""
1,2008-08-11,1,b'Why wont America and Nato help us? If they w...,b'Bush puts foot down on Georgian conflict',"b""Jewish Georgian minister: Thanks to Israeli ...",b'Georgian army flees in disarray as Russians ...,"b""Olympic opening ceremony fireworks 'faked'""",b'What were the Mossad with fraudulent New Zea...,b'Russia angered by Israeli military sale to G...,b'An American citizen living in S.Ossetia blam...,...,b'Israel and the US behind the Georgian aggres...,"b'""Do not believe TV, neither Russian nor Geor...",b'Riots are still going on in Montreal (Canada...,b'China to overtake US as largest manufacturer',b'War in South Ossetia [PICS]',b'Israeli Physicians Group Condemns State Tort...,b' Russia has just beaten the United States ov...,b'Perhaps *the* question about the Georgia - R...,b'Russia is so much better at war',"b""So this is what it's come to: trading sex fo..."
2,2008-08-12,0,b'Remember that adorable 9-year-old who sang a...,"b""Russia 'ends Georgia operation'""","b'""If we had no sexual harassment we would hav...","b""Al-Qa'eda is losing support in Iraq because ...",b'Ceasefire in Georgia: Putin Outmaneuvers the...,b'Why Microsoft and Intel tried to kill the XO...,b'Stratfor: The Russo-Georgian War and the Bal...,"b""I'm Trying to Get a Sense of This Whole Geor...",...,b'U.S. troops still in Georgia (did you know t...,b'Why Russias response to Georgia was right',"b'Gorbachev accuses U.S. of making a ""serious ...","b'Russia, Georgia, and NATO: Cold War Two'",b'Remember that adorable 62-year-old who led y...,b'War in Georgia: The Israeli connection',b'All signs point to the US encouraging Georgi...,b'Christopher King argues that the US and NATO...,b'America: The New Mexico?',"b""BBC NEWS | Asia-Pacific | Extinction 'by man..."
3,2008-08-13,0,b' U.S. refuses Israel weapons to attack Iran:...,"b""When the president ordered to attack Tskhinv...",b' Israel clears troops who killed Reuters cam...,b'Britain\'s policy of being tough on drugs is...,b'Body of 14 year old found in trunk; Latest (...,b'China has moved 10 *million* quake survivors...,"b""Bush announces Operation Get All Up In Russi...",b'Russian forces sink Georgian ships ',...,b'Elephants extinct by 2020?',b'US humanitarian missions soon in Georgia - i...,"b""Georgia's DDOS came from US sources""","b'Russian convoy heads into Georgia, violating...",b'Israeli defence minister: US against strike ...,b'Gorbachev: We Had No Choice',b'Witness: Russian forces head towards Tbilisi...,b' Quarter of Russians blame U.S. for conflict...,b'Georgian president says US military will ta...,b'2006: Nobel laureate Aleksander Solzhenitsyn...
4,2008-08-14,1,b'All the experts admit that we should legalis...,b'War in South Osetia - 89 pictures made by a ...,b'Swedish wrestler Ara Abrahamian throws away ...,b'Russia exaggerated the death toll in South O...,b'Missile That Killed 9 Inside Pakistan May Ha...,"b""Rushdie Condemns Random House's Refusal to P...",b'Poland and US agree to missle defense deal. ...,"b'Will the Russians conquer Tblisi? Bet on it,...",...,b'Bank analyst forecast Georgian crisis 2 days...,"b""Georgia confict could set back Russia's US r...",b'War in the Caucasus is as much the product o...,"b'""Non-media"" photos of South Ossetia/Georgia ...",b'Georgian TV reporter shot by Russian sniper ...,b'Saudi Arabia: Mother moves to block child ma...,b'Taliban wages war on humanitarian aid workers',"b'Russia: World ""can forget about"" Georgia\'s...",b'Darfur rebels accuse Sudan of mounting major...,b'Philippines : Peace Advocate say Muslims nee...

In [22]:
q("SELECT COUNT(*) FROM data")

   COUNT(*)
0      1986

In [23]:
df.dtypes

date     object
label     int64
top1     object
top2     object
top3     object
top4     object
top5     object
top6     object
top7     object
top8     object
top9     object
top10    object
top11    object
top12    object
top13    object
top14    object
top15    object
top16    object
top17    object
top18    object
top19    object
top20    object
top21    object
top22    object
top23    object
top24    object
top25    object
dtype: object

My table has 1986 rows.

One Row = One day

Numbers to add up: label

Groups to Compare: year, month

In [24]:
q("""
SELECT COUNT(*) AS down_days
FROM data
WHERE label = 0
""")

   down_days
0        924

In [25]:
q("""
SELECT label, COUNT(*) AS days,
  SUM(1) AS total
FROM data
GROUP BY label
""")

   label  days  total
0      0   924    924
1      1  1062   1062

In [26]:
q("""
SELECT date,
  SUM(label) AS total
FROM data
GROUP BY date
ORDER BY total DESC
LIMIT 2
""")

         date  total
0  2016-07-01      1
1  2016-06-30      1

Q1. How many days had a label of 1 (market up)?”

In [27]:
q("""
SELECT COUNT(*) AS up_days
FROM data
WHERE label = 1
""")

   up_days
0     1062

Q2. Which year had the most days with a label of 1?”

In [28]:
q("""
SELECT SUBSTR(date, 1, 4) AS year, SUM(label) AS up_days
FROM data
GROUP BY year
ORDER BY up_days DESC
LIMIT 2
""")

   year  up_days
0  2013      146
1  2010      143

Q3. What are the top 5 months in 2008 with the most down days?

In [29]:
q("""
SELECT SUBSTR(date, 1, 7) AS month,
  COUNT(*) AS down_days
FROM data
WHERE label = 0
  AND SUBSTR(date, 1, 4) = '2008'
GROUP BY month
ORDER BY down_days DESC
LIMIT 5
""")

     month  down_days
0  2008-10         16
1  2008-12         11
2  2008-11         10
3  2008-09         10
4  2008-08          7